In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv('/content/adult_with_headers.csv')
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [26]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [27]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [ ]:
df['capital_gain'].value_counts()

capital_gain
0        8224
15024     104
7688       77
7298       61
99999      43
         ...
3942        1
401         1
2062        1
22040       1
9562        1
Name: count, Length: 99, dtype: int64

In [ ]:
df['capital_loss'].value_counts()

capital_loss
0       8534
1902      64
1977      49
1887      35
1485      17
        ...
2547       1
419        1
1651       1
653        1
4356       1
Name: count, Length: 73, dtype: int64

In [7]:
from sklearn.preprocessing import StandardScaler
numerical_features = ['age','fnlwgt','education_num','hours_per_week','capital_gain','capital_loss']

In [8]:
scaler = StandardScaler()

In [9]:
df[numerical_features]= scaler.fit_transform(df[numerical_features])

In [10]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit and transform the selected features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

Standard Scaling is preferred when the features are normally distributed. It ensures that each feature contributes equally to the distance computations, which is important for algorithms like k-means clustering and principal component analysis.

Min-Max Scaling is preferred when you need the data to be within a specific range, such as [0, 1]. This is particularly useful for algorithms that do not assume any distribution of data, like neural networks and any algorithm relying on gradient descent optimization.

In [7]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

In [ ]:
df['workclass'].value_counts()

workclass
Private             6225
Self-emp-not-inc     721
Local-gov            568
?                    531
State-gov            354
Self-emp-inc         316
Federal-gov          248
Without-pay            1
Never-worked           1
Name: count, dtype: int64

In [ ]:
df['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [ ]:
df['marital_status'].value_counts()

marital_status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [ ]:
df['relationship'].value_counts()

relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [ ]:
df['race'].value_counts()

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [ ]:
df['native_country'].value_counts()

native_country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Laos                             18
Thailand                         18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [11]:
df = pd.get_dummies(df,columns=['race','sex'])

In [13]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding for other categorical features
label_encoders = {}
for column in ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'native_country']:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

In [36]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,hours_per_week,native_country,income,race_ Amer-Indian-Eskimo,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White,sex_ Female,sex_ Male
0,0.301370,7,0.044302,9,0.800000,4,1,1,0.02174,0.0,0.397959,39,<=50K,False,False,False,False,True,False,True
1,0.452055,6,0.048238,9,0.800000,2,4,0,0.00000,0.0,0.122449,39,<=50K,False,False,False,False,True,False,True
2,0.287671,4,0.138113,11,0.533333,0,6,1,0.00000,0.0,0.397959,39,<=50K,False,False,False,False,True,False,True
3,0.493151,4,0.151068,1,0.400000,2,6,0,0.00000,0.0,0.397959,39,<=50K,False,False,True,False,False,False,True
4,0.150685,4,0.221488,9,0.800000,2,10,5,0.00000,0.0,0.397959,5,<=50K,False,False,True,False,False,True,False

Choosing between One-Hot Encoding and Label Encoding depends on the nature of your data and the machine learning algorithm you're using. One-Hot Encoding is preferable for categorical variables with fewer categories and no intrinsic order, while Label Encoding is more suitable for variables with many categories or where an ordinal relationship exists.

Feature Engineering

creating new features

1. Age group:
Rationale:Grouping age into categories can capture non-linear relationships between age and income. For instance, certain age groups might have higher or lower income tendencies due to career stages or life circumstances.

2.Capital Gain Indicator:

Rationale: A binary indicator for whether an individual has any capital gain might be informative, as those with capital gains could have a higher likelihood of earning more than $50K.

In [14]:
df['age_group']= pd.cut(df['age'],bins=[0,25,45,65,100], labels=['0-25','26-45','46-55','66+'])

In [15]:
# Creating capital gain indicator
df['capital_gain_indicator'] = df['capital_gain'].apply(lambda x: 1 if x > 0 else 0)

1. Log Transformation of capital-gain:

Rationale: The capital-gain feature is often highly skewed, with most people having zero or low capital gains but a few having very high gains. Applying a log transformation can reduce skewness and make the distribution more normal, which can improve the performance of some machine learning algorithms.

In [16]:
import numpy as np

# Log transformation for capital gain
df['capital_gain'] = df['capital_gain'].apply(lambda x: np.log(x + 1))  # Adding 1 to avoid log(0)

In [17]:
df.dtypes

age                          float64
workclass                      int64
fnlwgt                       float64
education                      int64
education_num                float64
marital_status                 int64
occupation                     int64
relationship                   int64
capital_gain                 float64
capital_loss                 float64
hours_per_week               float64
native_country                 int64
income                        object
race_ Amer-Indian-Eskimo       uint8
race_ Asian-Pac-Islander       uint8
race_ Black                    uint8
race_ Other                    uint8
race_ White                    uint8
sex_ Female                    uint8
sex_ Male                      uint8
age_group                   category
capital_gain_indicator         int64
dtype: object

Feature Scaling

In [18]:
from sklearn.ensemble import IsolationForest

# Initialize Isolation Forest
iso_forest = IsolationForest(contamination=0.01)  # Adjust contamination as needed

# Fit the Isolation Forest to the data and predict outliers
outliers = iso_forest.fit_predict(df.drop('income', axis=1))

# Remove outliers
df_cleaned = df[outliers == 1]

ValueError: could not convert string to float: '0-25'

In [19]:
!pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.10/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2024.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)

In [20]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import IsolationForest
import ppscore as pps


# Assuming 'df' is your preprocessed dataframe

# One-Hot Encode Categorical Features
categorical_features = df.select_dtypes(include=['object', 'category']).columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_data = encoder.fit_transform(df[categorical_features])
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_features))

# Concatenate Encoded Features with Numerical Features
numerical_features = df.drop(columns=categorical_features.union(['income']))
df_encoded = pd.concat([numerical_features, encoded_df], axis=1)

# Initialize Isolation Forest
iso_forest = IsolationForest(contamination=0.01)  # Adjust contamination as needed

# Fit the model and predict outliers
outliers = iso_forest.fit_predict(df_encoded)

# Remove outliers from the original dataframe
df_cleaned = df[outliers == 1]

print(f"Original dataframe shape: {df.shape}")
print(f"Cleaned dataframe shape: {df_cleaned.shape}")


# Calculate PPS matrix
pps_matrix = pps.matrix(df_cleaned)

# Extract relevant PPS scores (predictive power of each feature on 'income')
pps_income = pps_matrix[pps_matrix['y'] == 'income'][['x', 'ppscore']].sort_values(by='ppscore', ascending=False)

# Calculate correlation matrix
correlation_matrix = df_cleaned.corr()

# Print PPS and correlation for comparison
print("\nPredictive Power Score (PPS) for 'income':\n", pps_income)
print("\nCorrelation Matrix:\n", correlation_matrix)

# You can further analyze and visualize the PPS and correlation matrices
# to gain deeper insights into feature relationships.

Original dataframe shape: (32561, 22)
Cleaned dataframe shape: (32235, 22)

/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33

Predictive Power Score (PPS) for 'income':
                             x       ppscore
276                    income  1.000000e+00
188              capital_gain  2.890031e-01
78                  education  2.419249e-01
100             education_num  2.419249e-01
474    capital_gain_indicator  2.346007e-01
210              capital_loss  1.616380e-01
34                  workclass  9.643287e-02
232            hours_per_week  1.375428e-02
12                        age  8.295219e-03
166              relationship  1.728522e-07
144                occupation  1.728522e-07
122            marital_status  1.728522e-07
298  race_ Amer-Indian-Eskimo  1.728522e-07
320  race_ Asian-Pac-Islander  1.728522e-07
342               race_ Black  1.728522e-07
364               race_ Other  1.728522e-07
386               race_ White  1.728522e-07
408               sex_ Female  1.728522e-07
430                 sex_ Male  1.728522e-07
452                 age_group  1.263094e-07
56                     fnlwgt  0.000000e+00
254            native_country  0.000000e+00

Correlation Matrix:
                                age  workclass    fnlwgt  education  \
age                       1.000000   0.000913 -0.077251  -0.015205
workclass                 0.000913   1.000000 -0.016470   0.016686
fnlwgt                   -0.077251  -0.016470  1.000000  -0.028395
education                -0.015205   0.016686 -0.028395   1.000000
education_num             0.032636   0.048115 -0.043467   0.355118
marital_status           -0.268201  -0.062506  0.027765  -0.034381
occupation               -0.022461   0.250484  0.002207  -0.024462
relationship             -0.267323  -0.088742  0.007343  -0.006564
capital_gain              0.087185   0.033938 -0.003050   0.032732
capital_loss              0.056443   0.013991 -0.010109   0.018192
hours_per_week            0.066588   0.136564 -0.018436   0.050852
native_country            0.002609  -0.004167 -0.053667   0.064377
race_ Amer-Indian-Eskimo -0.009958  -0.019800 -0.062577  -0.002629
race_ Asian-Pac-Islander -0.014136   0.001930 -0.050080   0.012928
race_ Black              -0.019755  -0.056688  0.115302  -0.017352
race_ Other              -0.032494  -0.013554  0.006739  -0.024604
race_ White               0.034351   0.055452 -0.057003   0.015130
sex_ Female              -0.090086  -0.092032 -0.028000   0.033183
sex_ Male                 0.090086   0.092032  0.028000  -0.033183
capital_gain_indicator    0.115100   0.019283 -0.007754   0.023824

                          education_num  marital_status  occupation  \
age                            0.032636       -0.268201   -0.022461
workclass                      0.048115       -0.062506    0.250484
fnlwgt                        -0.043467        0.027765    0.002207
education                      0.355118       -0.034381   -0.024462
education_num                  1.000000       -0.064980    0.107292
marital_status                -0.064980        1.000000   -0.008755
occupation                     0.107292       -0.008755    1.000000
relationship                  -0.095656        0.189214   -0.074849
capital_gain                   0.131465       -0.051296    0.026559
capital_loss                   0.079847       -0.035492    0.018327
hours_per_week                 0.144723       -0.190164    0.078652
native_country                 0.058383       -0.026635   -0.010531
race_ Amer-Indian-Eskimo      -0.031746       -0.001570   -0.003482
race_ Asian-Pac-Islander       0.058066        0.021696    0.004367
race_ Black                   -0.078533        0.082479   -0.012858
race_ Other                   -0.044077        0.018582    0.002377
race_ White                    0.057250       -0.084104    0.009017
sex_ Female                   -0.011174        0.129797   -0.078891
sex_ Male                      0.011174       -0.129797    0.078891
capital_gain_indicator         0.109564       -0.063539    0.015630

                          relationship  capital_gain  capital_loss  \
age                          -0.267323      0.087185      0.056443
workclass                    -0.088742      0.033938      0.013991
fnlwgt                        0.007343     -0.003050     -0.010109
education                    -0.006564      0.032732      0.018192
education_num                -0.095656      0.131465      0.079847
marital_status                0.189214     -0.051296     -0.035492
occupation                   -0.074849      0.026559      0.018327
relationship                  1.000000     -0.084907     -0.065392
capital_gain                 -0.084907      1.000000     -0.035212
capital_loss                 -0.065392     -0.035212      1.000000
hours_per_week               -0.249649      0.084314      0.052533
native_country                0.000597      0.023457      0.009794
race_ Amer-Indian-Eskimo      0.020789     -0.009443     -0.013331
race_ Asian-Pac-Islander      0.003504     -0.019500     -0.003699
race_ Black                   0.135561     -0.037875     -0.027388
race_ Other                   0.012443     -0.013306     -0.007472
race_ White                  -0.124343      0.047247      0.030312
sex_ Female                   0.579699     -0.073295     -0.048478
sex_ Male                    -0.579699      0.073295      0.048478
capital_gain_indicator       -0.089988      0.560826     -0.062787

                          hours_per_week  native_country  \
age                             0.066588        0.002609
workclass                       0.136564       -0.004167
fnlwgt                         -0.018436       -0.053667
education                       0.050852        0.064377
education_num                   0.144723        0.058383
marital_status                 -0.190164       -0.026635
occupation                      0.078652       -0.010531
relationship                   -0.249649        0.000597
capital_gain                    0.084314        0.023457
capital_loss                    0.052533        0.009794
hours_per_week                  1.000000        0.000808
native_country                  0.000808        1.000000
race_ Amer-Indian-Eskimo       -0.002700        0.018300
race_ Asian-Pac-Islander       -0.011069       -0.192978
race_ Black                    -0.053627       -0.000920
race_ Other                    -0.009150       -0.099209
race_ White                     0.053478        0.114985
sex_ Female                    -0.229107        0.011699
sex_ Male                       0.229107       -0.011699
capital_gain_indicator          0.073528        0.025763

                          race_ Amer-Indian-Eskimo  race_ Asian-Pac-Islander  \
age                                      -0.009958                 -0.014136
workclass                                -0.019800                  0.001930
fnlwgt                                   -0.062577                 -0.050080
education                                -0.002629                  0.012928
education_num                            -0.031746                  0.058066
marital_status                           -0.001570                  0.021696
occupation                               -0.003482                  0.004367
relationship                              0.020789                  0.003504
capital_gain                             -0.009443                 -0.019500
capital_loss                             -0.013331                 -0.003699
hours_per_week                           -0.002700                 -0.011069
native_country                            0.018300                 -0.192978
race_ Amer-Indian-Eskimo                  1.000000                 -0.016648
race_ Asian-Pac-Islander                 -0.016648                  1.000000
race_ Black                              -0.030617                 -0.056148
race_ Other                              -0.008338                 -0.015291
race_ White                              -0.236327                 -0.433395
sex_ Female                               0.006299                 -0.002671
sex_ Male                                -0.006299                  0.002671
capital_gain_indicator                   -0.007106                 -0.023212

                          race_ Black  race_ Other  race_ White  sex_ Female  \
age                         -0.019755    -0.032494     0.034351    -0.090086
workclass                   -0.056688    -0.013554     0.055452    -0.092032
fnlwgt                       0.115302     0.006739    -0.057003    -0.028000
education                   -0.017352    -0.024604     0.015130     0.033183
education_num               -0.078533    -0.044077     0.057250    -0.011174
marital_status               0.082479     0.018582    -0.084104     0.129797
occupation                  -0.012858     0.002377     0.009017    -0.078891
relationship                 0.135561     0.012443    -0.124343     0.579699
capital_gain                -0.037875    -0.013306     0.047247    -0.073295
capital_loss                -0.027388    -0.007472     0.030312    -0.048478
hours_per_week              -0.053627    -0.009150     0.053478    -0.229107
native_country              -0.000920    -0.099209     0.114985     0.011699
race_ Amer-Indian-Eskimo    -0.030617    -0.008338    -0.236327     0.006299
race_ Asian-Pac-Islander    -0.056148    -0.015291    -0.433395    -0.002671
race_ Black                  1.000000    -0.028121    -0.797036     0.112934
race_ Other                 -0.028121     1.000000    -0.217066     0.012740
race_ White                 -0.797036    -0.217066     1.000000    -0.098449
sex_ Female                  0.112934     0.012740    -0.098449     1.000000
sex_ Male                   -0.112934    -0.012740     0.098449    -1.000000
capital_gain_indicator      -0.044478    -0.018946     0.055383    -0.075875

                          sex_ Male  capital_gain_indicator
age                        0.090086                0.115100
workclass                  0.092032                0.019283
fnlwgt                     0.028000               -0.007754
education                 -0.033183                0.023824
education_num              0.011174                0.109564
marital_status            -0.129797               -0.063539
occupation                 0.078891                0.015630
relationship              -0.579699               -0.089988
capital_gain               0.073295                0.560826
capital_loss               0.048478               -0.062787
hours_per_week             0.229107                0.073528
native_country            -0.011699                0.025763
race_ Amer-Indian-Eskimo  -0.006299               -0.007106
race_ Asian-Pac-Islander   0.002671               -0.023212
race_ Black               -0.112934               -0.044478
race_ Other               -0.012740               -0.018946
race_ White                0.098449                0.055383
sex_ Female               -1.000000               -0.075875
sex_ Male                  1.000000                0.075875
capital_gain_indicator     0.075875                1.000000

/usr/local/lib/python3.10/dist-packages/ppscore/calculation.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return f1_diff / scale_range  # 0.1/0.3 = 0.33
<ipython-input-20-712065c6f696>:40: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df_cleaned.corr()

Predictive Power Score (PPS):

PPS measures the ability of one feature to predict another. It provides a more nuanced view of feature relationships compared to correlation, as it can detect non-linear relationships and is less sensitive to outliers.

Correlation Matrix:

The correlation matrix shows the linear relationship between features. It's a good starting point but might miss complex relationships.